name: mlenv
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - asttokens=3.0.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.3
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libavif=1.1.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.3
  - requests=2.32.4
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.0
      - agate==1.13.0
      - agate-dbf==0.2.3
      - agate-excel==0.4.1
      - agate-sql==0.7.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - attrs==25.3.0
      - av==15.0.0
      - babel==2.17.0
      - banal==1.0.6
      - bert-score==0.3.13
      - bitsandbytes==0.47.0
      - bleach==6.2.0
      - click==8.2.1
      - contourpy==1.3.3
      - csvkit==2.1.0
      - cycler==0.12.1
      - dataset==1.6.2
      - datasets==4.0.0
      - dbfread==2.0.7
      - dill==0.3.8
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - flash-attn==2.8.3
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - isodate==0.7.2
      - joblib==1.5.1
      - kaggle==1.7.4.5
      - kiwisolver==1.4.9
      - leather==0.4.0
      - mako==1.3.10
      - matplotlib==3.10.5
      - multidict==6.6.3
      - multiprocess==0.70.16
      - ninja==1.13.0
      - olefile==0.47
      - open-clip-torch==2.24.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.1
      - parsedatetime==2.6
      - peft==0.17.0
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pytz==2025.2
      - qwen-vl-utils==0.0.11
      - regex==2025.7.34
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.34.1
      - smmap==5.0.2
      - sqlalchemy==1.4.54
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.55.0
      - trl==0.21.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.21.1
      - webencodings==0.5.1
      - xlrd==2.0.2
      - xxhash==3.5.0
      - yarl==1.20.1
